spring:
  application:
    name: auth-server
  profiles:
    active: prod
  session:
    redis:
      flush-mode: on_save
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:mysql://s4.java21.net:13306/project_be11_team3_dev
    username: project_be11_team3
    password: ${PASSWORD}
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  jwt:
    secret: "저는개인적으로에스파의윈터가짱이라고생각합니다반박시그대말이다맞음"
